# A Pythonic Exploration of Linear Algebra: Scalars, Vectors, Matrices, and Tensors
**by Lorenzo Arcioni**

Linear algebra is a branch of mathematics that deals with the study of vector spaces and linear transformations between them. It provides the fundamental tools and concepts for analyzing systems of linear equations, solving problems in geometry, and studying the properties of mathematical objects such as scalars, vectors, matrices, and tensors.

## Scalars

Scalars are elements of a field, such as ℝ, representing quantities that possess only magnitude, such as temperature, mass, distance, or time. Scalars have zero dimensions, and they are considered point values in a mathematical space. Typically denoted by lowercase letters (e.g., a, b, c), scalars are treated as constants. They can be real numbers, complex numbers, or elements from other mathematical fields.

Let’s now represent a scalar in Python using the well known mathematical library NumPy.

In [1]:
import numpy as np

## Representing a scalar as aNumPy object

# Creating a scalar
a = np.array(5)

# Displaying the scalar value
print("Scalar Value:", a)

# Displaying the scalar shape
print("Scalar Shape:", a.shape)

Scalar Value: 5
Scalar Shape: ()


Since a scalar has no dimensions, its shape is represented as an empty tuple.

## Vectors

A vector is an ordered collection of scalars that represents a quantity with both magnitude and direction. Vectors are used to describe various physical quantities, such as displacement, velocity, and force.
In a geometric sense, they can be visualized as directed line segments with a specific length and direction in space.

Vectors are typically denoted using lowercase letters with an arrow above them or by bold typeface (e.g., $v$, $w$, $z$). In a vector, elements can be accessed along its dimension using their position/index.

    Remember that in Python, indexing starts at position 0.

In this example, we create a vector
$$
\vec v = \begin{bmatrix}
2\\
4\\
6\\
8
\end{bmatrix} \in \mathbb{R}^3
$$

and by using indexing, we can easily access its components. For instance, to access its third component, we write $v[2]$.

Here there is a practical code example.

In [2]:
import numpy as np

# Representing a vector as a NumPy object 
v = np.array([2, 4, 6, 8])

# Displaying the vector
print("Vector:", v)

# Displaying the vector shape
print("Vector shape:", v.shape)

# Accessing the third element in the vector
element_3 = v[2]
print("The third element:", element_3)

Vector: [2 4 6 8]
Vector shape: (4,)
The third element: 6


Vectors have one dimension, so the shape of a vector is a 1-dimensional tuple $(n)$, where n is the number of elements in the vector.

So far, everything very elegant, but have you ever wondered how to access more than one element (scalar) of a vector at a time? For instance, if you wanted to access only the last two scalars of a vector, how could you accomplish that?

Well, the following code explains exactly how to achieve this result.

In [1]:
import numpy as np

# Representing a vector as a NumPy object 
v = np.array([2, 4, 6, 8])

# Displaying just the last 2 vector components
print("Subvector:", v[-2:])

Subvector: [6 8]


This way, we have obtained a sub-vector containing only the last two components of vector v.

    Remember that, in Python, when using negative indexes, we are referencing elements from the end of the vector. For instance, v[-1] refers to the last element, v[-2] to the second-to-last, and so forth.

In Python, the “:” is used for slicing arrays. It allows you to select a range of elements along a particular axis in an array. Here’s a brief explanation of how “:” works in indexing with NumPy:

1. **Selecting a Range:** `array[start:stop]`: Selects elements starting from the index start up to, but not including, the index stop.
2. **Omitting Start or Stop:** If start is omitted, it defaults to the beginning of the axis (index 0). If stop is omitted, it defaults to the end of the axis.
3. **Selecting Every Nth Element:** `array[start:stop:step]`: Selects elements starting from start up to, but not including, stop, with a step size of step.

## Matrices

A matrix is a structured arrangement of vectors of scalars. Think of it as a grid or table where each entry holds a value. Matrices are often used to represent data, perform mathematical operations, and describe transformations in various fields such as mathematics, computer science, physics, and engineering. The number of rows and columns in a matrix defines its dimensions, and individual elements within it can be manipulated to solve problems or analyse relationships between quantities.

>In matrices, just like in vectors, it is possible to use indexing to access the elements of the matrix.

In this example, we’ll demonstrate how to create a matrix using NumPy and how to access its components.

In [ ]:
import numpy as np

# Representing a matrix as a NumPy object
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Displaying the matrix
print("Matrix:")
print(A)

# Displaying the matrix shape
print("Matrix shape:", A.shape)

# Accessing the element at row 2, column 3
element_23 = A[1, 2]
print("Element at row 2, column 3:", element_23)

A matrix is characterized by its shape, expressed as a 2-dimensional tuple $(m, n)$, where m denotes the number of rows and n the number of columns. Conventionally, matrices are represented by uppercase bold letters, such as $\textbf{A}$, $\textbf{B}$, and $\textbf{C}$.

Of course, the same explanation given above for vectors also applies to matrices. For instance, if you wanted to access only the second row of matrix $\textbf{A}$ as a vector, how could you accomplish that?

The following code explains exactly how to achieve this result.

In [ ]:
import numpy as np

# Representing a matrix as a NumPy object
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Get just the second row as a vector
print(A[1, :])

So, in this example we have selected only the second row (that belong to the first dimension) of the matrix and all the scalars of the second dimension. Obviously, “:” can be used along multiple axes to create more complex slices. For example, `array[:, 1:3]` selects all rows and columns $1$ to $2$ of a $2D$ array.

## Tensors

Tensors are mathematical objects that generalize the concepts of scalars, vectors, and matrices to higher dimensions.
They are multi-dimensional arrays of numerical values. In the context of Linear Algebra, tensors can be seen as higher-order generalizations of matrices.

    Scalars are 0th-order tensors, vectors are 1st-order tensors, matrices are 2nd-order tensors, and so on.

The shape of a tensor is an n-dimensional tuple $(d1,d2,…,dn)$, where di represents the size of the $i$-th dimension.

Usually, tensors are represented by uppercase bold letters (similar to matrices), but with a different calligraphic style, such as 𝓣 or 𝓦.

>In tensors, just like in vectors and matrices, it is possible to use indexing to access the elements of the tensor.

In [2]:
import numpy as np

# Creating a 3-dimensional tensor
T = np.array([[[1, 2, 3],
               [4, 5, 6]],
               
              [[7, 8, 9],
               [10, 11, 12]],
               
              [[13, 14, 15],
               [16, 17, 18]]
])

# Displaying the tensor
print("3-dimensional Tensor:")
print(T)

# Accessing individual elements by indexing
element_211 = T[1, 0, 1]
print("Element at depth 2, row 1, column 2:", element_211)

3-dimensional Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Element at depth 2, row 1, column 2: 8


As you may easily imagine, the same logic applied to matrices and vectors also extends to tensors when it comes to slicing.

In the example below, you see how to use slicing in a tensor.

In [3]:
import numpy as np

# Creating a 3D tensor (3x3x3) for the example
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

# Slicing along all dimensions
slice_along_depth = T[1:, ::2, -2:]

print("Tensor:")
print(T)
print("Slice along the depth (from the second depth onwards):")
print(slice_along_depth)

Tensor:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Slice along the depth (from the second depth onwards):
[[[11 12]
  [17 18]]

 [[20 21]
  [26 27]]]


In this slightly more complex example:

- `1: `selects elements starting from the second depth (index 1) to the end of the depth dimension.
- `::2` selects every second element along the second dimension (rows).
- `-2:` selects the last two elements along the third dimension (columns).

Understanding tensors is crucial in fields that involve higher-dimensional data and complex relationships between variables. While the geometric interpretation becomes challenging as the order increases, the mathematical concepts remain consistent.

# Conclusions

As we conclude this exploration, we’ve merely scratched the surface of the captivating algebraic objects pivotal to Machine Learning. Today’s journey serves as an introductory glimpse into the intricate world of Linear Algebra. Our adventure, however, has just begun. In upcoming articles, we’ll delve into more advanced topics, unravelling the nuances and intricate applications of these tools. This article serves as a beginner’s guide, laying the foundation for deeper explorations into the vast realms of Linear Algebra and Machine Learning. Stay tuned for more in-depth insights and sophisticated discussions in the articles to come, where we’ll unravel the full potential of these mathematical constructs in shaping the landscape of Artificial Intelligence.
