# Linear Algebra exercises

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
from sympy import Matrix, latex
from IPython.display import display, Latex

Consider these two matrices

$$\large
A = \begin{bmatrix}
1 \ \ 2 \ \ 3\\
4 \ \ 5 \ \ 6\\
7 \ \ 8 \ \ 9\\
\end{bmatrix} \quad
B = \begin{bmatrix}
1 \ \ 1 \ \ 0\\
0 \ \ 1 \ \ 1 \\
1 \ \ 0 \ \ 1\\
\end{bmatrix}
$$

Calculate the product $\textbf A \cdot \textbf B$ and $\textbf B \cdot \textbf A$.

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

B = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

A_B = A @ B
B_A = B @ A

print("A @ B =\n", A_B)
print("B @ A =\n", B_A)

A @ B =
 [[ 4  3  5]
 [10  9 11]
 [16 15 17]]
B @ A =
 [[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


Find the set of all inhomogeneous linear systems $\textbf A\vec x = \vec b$ where 

$$\large
A = \left[\begin{matrix}1 & -1 & 0 & 0 & 1\\1 & 1 & 0 & -3 & 0\\2 & -1 & 0 & 1 & -1\\-1 & 2 & 0 & -2 & -1\end{matrix}\right]\quad
b = \begin{bmatrix}
3 \\
6 \\
5 \\
-1
\end{bmatrix}
$$

In [23]:
A = np.array([
    [1, -1, 0, 0, 1],
    [1, 1, 0, -3, 0],
    [2, -1, 0, 1, -1],
    [-1, 2, 0,-2, -1],
])

b = np.array([
    [3, 6, 5, -1]
]).T

A = sp.Matrix(A)
b = sp.Matrix(b)

sol, params = A.gauss_jordan_solve(b)

display(Latex("$\Large " + latex(A) + " \cdot " + latex(Matrix(["x_{}".format(i) for i in range(1, A.shape[1]+1)])) + " = " + latex(b) +"$"))

display(Latex("$\Large " + latex(A.col_insert(6, b).rref()) +"$"))

display(Latex("$\Large " + latex(Matrix(["x_{}".format(i) for i in range(1, A.shape[1]+1)])) + " = " + latex(sol) + "$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [63]:
'''
Aug12-2018
Mahesh Babu Mariappan (https://www.linkedin.com/in/mahesh-babu-mariappan)
Source code for example of a 4d tensor
results:
x.shape
x.ndim
(4, 2, 3, 4)
4
'''

import numpy as np

A = np.array(
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
  ]
)

B = np.array(
  [
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [1, 0, 1, 0],
  ]
)

x  = np.array(
  [
    [
      [ 
        [1,2,3,6],
        [4,5,6,6],
        [7,6,3,6]
      ],
      [ 
        [5,4,5,7],
        [4,5,7,7],
        [3,6,4,7] 
      ],
      [
        [1,2,3,4],
        [4,5,6,4],
        [7,6,3,4]
      ],
      [
        [1,2,3,4],
        [4,5,6,4],
        [7,6,3,4]
      ],
    ],
    [
      [ 
        [1,2,3,3],
        [4,5,6,3],
        [7,6,3,3]
      ],
      [ 
        [5,4,5,8],
        [4,5,7,8],
        [3,6,4,8] 
      ],
      [
        [1,2,3,3],
        [4,5,6,3],
        [7,6,3,3]
      ],
      [
        [1,2,3,4],
        [4,5,6,4],
        [7,6,3,4]
      ],
    ],
    [
      [ 
        [1,2,3,9],
        [4,5,6,9],
        [7,6,3,9]
      ],
      [ 
        [5,4,5,4],
        [4,5,7,4],
        [3,6,4,4] 
      ],
      [
        [1,2,3,2],
        [4,5,6,2],
        [7,6,3,2]
      ],
      [
        [1,2,3,4],
        [4,5,6,4],
        [7,6,3,4]
      ],
    ]
  ]
)


print(x.shape)
print(x.ndim)

v  = np.array(
  [
    [
      [ 
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ],
      [ 
        [5,4,5,],
        [4,5,7,],
        [3,6,4,] 
      ],
      [
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ]
    ],
    [
      [ 
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ],
      [ 
        [5,4,5,],
        [4,5,7,],
        [3,6,4,] 
      ],
      [
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ]
    ],
    [
      [ 
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ],
      [ 
        [5,4,5,],
        [4,5,7,],
        [3,6,4,] 
      ],
      [
        [1,2,3,],
        [4,5,6,],
        [7,6,3,]
      ]
    ],
  ]
)

(3, 4, 3, 4)
4


In [64]:
x.shape

(3, 4, 3, 4)

In [65]:
v.shape

(3, 3, 3, 3)

In [69]:
np.tensordot(x, v)

ValueError: shape-mismatch for sum

In [213]:
import numpy as np

A = np.arange(12).reshape(2, 2, 3)
B = np.arange(3).reshape(3)

# Contrazione sugli assi 2 di A e 1 di B
result = np.tensordot(A, B, axes=((2), (0)))

print("A =\n", A)
print("Dimensione di A:", A.shape)
print("B =\n", B)
print("Dimensione di B:", B.shape)
print("Risultato:\n", result)
print("Risultato-shape:", result.shape)

A =
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Dimensione di A: (2, 2, 3)
B =
 [0 1 2]
Dimensione di B: (3,)
Risultato:
 [[ 5 14]
 [23 32]]
Risultato-shape: (2, 2)


In [200]:
import numpy as np

A = np.arange(12).reshape(2, 2, 3)
B = np.arange(18).reshape(2, 3, 3)

# Contrazione sugli assi 2 di A e 1 di B
result = np.tensordot(A, B, axes=((2, 1), (2, 0)))

print("A =\n", A)
print("Dimensione di A:", A.shape)
print("B =\n", B)
print("Dimensione di B:", B.shape)
print("Risultato:\n", result)
print("Risultato-shape:", result.shape)

A =
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Dimensione di A: (2, 2, 3)
B =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Dimensione di B: (2, 3, 3)
Risultato:
 [[127 172 217]
 [325 478 631]]
Risultato-shape: (2, 3)


In [153]:
A @ B

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [154]:
B@A

array([[10, 13],
       [28, 40]])