<a href="https://colab.research.google.com/github/lorenzo-arcioni/Applied-Mathematics-Hub/blob/main/Linear Algebra and Analytic Geometry/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Pythonic Exploration of Linear Algebra: Object Addition
**by Lorenzo Arcioni**

In this exploration, we dive into the core concept of object addition, an essential operation that lies at the heart of linear algebra, paving the way for a deeper understanding of mathematical structures and their real-world applications.

Scalar, vector, matrix, and tensor addition are fundamental operations that extend beyond mere mathematical operations; they are the building blocks for solving complex problems in various scientific and computational domains. Through the lens of NumPy, we embark on a journey to discover the elegance and efficiency with which we can perform these operations in a Pythonic manner.

According to mathematical theory, it is only possible to add two objects (scalars, vectors, matrices, and tensors) if and only if they have the same shape, meaning they have the same dimensions and the same number of elements for each dimension. But we will see that when we operate with NumPy, this rule does not always apply! In fact, in certain cases, we can add two objects even if they have different shapes.

## Scalar Addition

Scalar addition by another scalar involves adding two scalar values together, providing a straightforward yet crucial operation in mathematical computations.
This operation concerns the most common addition operation, the one we are accustomed to performing routinely.

In [7]:
# Importing necessary libraries
import numpy as np

# Example scalar values
a = np.array(5)
b = np.array(3)

# Scalar-scalar addition
c = a + b

# Display the result
print("The sum of", a, "and", b, "is", c)

The sum of 5 and 3 is 8


As you can see, it's the trivial addition.

## Vector Addition

In this segment, we focus on the addition of vectors, fundamental mathematical entities that play a crucial role in various scientific and computational applications. Vector sum is an element-wise operation, so with two generic vectors $\vec a$ and $\vec b$, their sum is defined as the element-wise sum of their components.

Geometrically, vector addition corresponds to placing the initial point of the second vector at the terminal point of the first vector and connecting the initial point of the first vector to the terminal point of the second vector.

Leveraging NumPy's inherent ability to perform element-wise operations, we effortlessly compute the sum of vectors using the $+$ operator. The resulting vector showcases how NumPy simplifies and enhances the efficiency of vector addition, making it an indispensable tool for mathematical operations in the Python ecosystem.

**Example**

In [8]:
import numpy as np

# Example vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perform vector addition
c = a + b
print("The sum of", a, "and", b, "is", c)

The sum of [1 2 3] and [4 5 6] is [5 7 9]


As mentioned in the introduction, it's possible to add together two objects of different dimensionalities, such as a scalar and a vector. In this case, the scalar is added to each element of the vector, resulting in a new vector where each element is the sum of the corresponding element in the original vector and the scalar.

**Example**

In [9]:
import numpy as np

# Define a scalar and a vector
scalar_value = 5
vector = np.array([1, 2, 3])

# Scalar-vector addition
result_vector = scalar_value + vector

# Display the original scalar, vector, and the result
print("Scalar Value:", scalar_value)
print("\nVector:")
print(vector)
print("\nResult of Scalar-Vector Addition:")
print(result_vector)

Scalar Value: 5

Vector:
[1 2 3]

Result of Scalar-Vector Addition:
[6 7 8]


Let's explore another type of sum using NumPy's sum function along a specific axis. The **numpy.sum** function allows us to calculate the sum of array elements along a specified axis.

Here's an example with a vector.

**Example**

In [10]:
# Importing necessary libraries
import numpy as np

# Example vector
v = np.array([1, .2, 3, 4])

# Calculating the sum of elements in the vector
v_sum = np.sum(v)

# Display the total sum
print("The sum of elements in the vector is", v_sum) # 8.2 = 1 + .2 + 3 + 4 = v_sum

The sum of elements in the vector is 8.2


This kind of sum, utilizing **numpy.sum** along a specified axis, is particularly powerful when dealing with multi-dimensional arrays. It allows us to focus on the summation operation along a specific dimension, providing a versatile tool for array manipulation and analysis. In the case of vectors, as illustrated in the example above, it conveniently computes the total sum of all elements in the array. However, as we delve into more complex data structures like matrices and tensors, specifying the axis becomes crucial for obtaining meaningful results and gaining insights into the structure of the data. Let's explore further with examples involving matrices and tensors to showcase the versatility of **numpy.sum** along different axes.

## Matrix Addition

Now, our focus shifts to matrices—two-dimensional arrays that serve as fundamental structures in various scientific and computational domains.

In the cell below, we define two example matrices, $\textbf{A}_{3,3}$ and $\textbf{B}_{3,3}$, as NumPy arrays. Leveraging NumPy's vectorized operations, the + operator facilitates the addition of these matrices element-wise. The resulting result_matrix showcases how NumPy streamlines matrix addition, providing a clear and concise syntax for handling complex mathematical operations.

**Example**

In [11]:
import numpy as np

# Matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matrix B
B = np.array([[9, 12, 0],
              [5, -5, 1],
              [-7, 8, 4.2]])

# Matrix addition
C = A + B

# Display the result
print("The sum of A and B is:\n", C)

The sum of A and B is:
 [[10.  14.   3. ]
 [ 9.   0.   7. ]
 [ 0.  16.  13.2]]


As you can see, two matrices can be added together only if they have the same 'shape'; indeed, in our case, the matrices have both the first and second dimensions equal.

But let's consider another example; let's take two matrices, $\textbf{A}_{3,5}$ and $\textbf{B}_{3,5}$, each with a size of 3x5, and calculate their sum using NumPy.

**Example**

In [12]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

B = np.array([[5, 4, 3, 2, 1],
              [10, 9, 8, 7, 6],
              [15, 14, 13, 12, 11]])

# Calculate the sum of matrices A and B
C = A + B

# Display the matrices and their sum
print("Sum of Matrices A and B:")
print(C)

Sum of Matrices A and B:
[[ 6  6  6  6  6]
 [16 16 16 16 16]
 [26 26 26 26 26]]


As you can see, the result is still a 3x5 matrix generated by the component-wise addition of the components of matrices $\textbf{A}_{3,5}$ and $\textbf{B}_{3,5}$.

As with vectors, matrices can also be added to objects of different shapes. In this example, we'll demonstrate both scalar-matrix addition and vector-matrix addition. When adding a scalar to a matrix, the scalar is added to each element of the matrix. Conversely, when adding a vector to a matrix, the vector is added element-wise to each corresponding column of the matrix. Both operations are performed element-wise.

In [13]:
import numpy as np

# Define a scalar, a vector, and a matrix
scalar_value = 5
vector = np.array([1, 2, 3])
matrix = np.array([[4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Scalar-matrix addition
scalar_matrix_result = scalar_value + matrix

# Vector-matrix addition
vector_matrix_result = vector + matrix

# Display the original scalar, vector, matrix, and the results
print("Scalar Value:", scalar_value)
print("\nVector:")
print(vector)
print("\nMatrix:")
print(matrix)
print("\nResult of Scalar-Matrix Addition:")
print(scalar_matrix_result)
print("\nResult of Vector-Matrix Addition:")
print(vector_matrix_result)

Scalar Value: 5

Vector:
[1 2 3]

Matrix:
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result of Scalar-Matrix Addition:
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

Result of Vector-Matrix Addition:
[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


We also notice that in matrices, it's possible to use the **numpy.sum** function to perform sums along the axes of a matrix. For instance, if we want to calculate the sum of elements along the columns of a matrix, we can specify the corresponding axis using the parameter `axis=0`. Conversely, to obtain the sum along the rows, we can use `axis=1`. This flexibility in axis specification allows us to obtain aggregated sums in specific directions within the matrix.

**Example**

In [14]:
import numpy as np

# Define a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the sum along the columns (axis=0)
column_sum = np.sum(matrix, axis=0)

# Calculate the sum along the rows (axis=1)
row_sum = np.sum(matrix, axis=1)

# Display the original matrix and the sums
print("Original Matrix:")
print(matrix)

print("\nSum along Columns (axis=0):")
print(column_sum)

print("\nSum along Rows (axis=1):")
print(row_sum)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum along Columns (axis=0):
[12 15 18]

Sum along Rows (axis=1):
[ 6 15 24]


In this example:

- We define a sample matrix.
- We use np.sum(matrix, axis=0) to calculate the sum along the columns (axis=0), which means that we are obtaining a new array where each element corresponds to the sum of the elements in the same column across all rows. This operation collapses the matrix along the vertical direction, providing insights into the total contribution of each column to the overall structure.
- We use np.sum(matrix, axis=1) to calculate the sum along the rows (axis=1), which means that we are obtaining an array where each element represents the sum of the elements in the same row across all columns. This horizontal summation allows us to understand the cumulative effect of each row within the matrix.

## Tensor Addition

We have reached the third and final section of today's topic. Tensor addition is an element-wise operation that involves adding tensors of the same shape. This means that, similar to what we've seen with matrices and vectors, the addition occurs between corresponding elements in the input tensors.

To perform tensor addition in Python using NumPy, we can use the same logic as in the previous operations, as NumPy extends its versatility to tensors as well. Let's see an example of how we could perform this operation with two 3D tensors.

**Example**

In [15]:
import numpy as np

# Manual definition of two 3D tensors
A = np.array([[
               [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]
              ],
               
              [
               [13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]
              ]
])

B = np.array([[
               [25, 26, 27, 28],
               [29, 30, 31, 32],
               [33, 34, 35, 36]
              ],
                     
              [
               [37, 38, 39, 40],
               [41, 42, 43, 44],
               [45, 46, 47, 48]
              ]
])

# Tensor addition
C = A + B

# Displaying tensor result of the addition
print("Sum of Tensors A and B:")
print(C)

Sum of Tensors A and B:
[[[26 28 30 32]
  [34 36 38 40]
  [42 44 46 48]]

 [[50 52 54 56]
  [58 60 62 64]
  [66 68 70 72]]]


With a bit of imagination, you will notice that it is possible to add scalars, vectors, and matrices to tensors.

In this example, we'll showcase the addition of a scalar, a vector, and a matrix to a 3D tensor. Similar to the previous cases, these operations are performed element-wise. The scalar is added to each element of the tensor, the vector is added element-wise to each corresponding subarray along the first axis, and the matrix is added element-wise to each corresponding subarray along the first axis.

**Example**

In [16]:
import numpy as np

# Define a scalar, a vector, a matrix, and a 3D tensor
scalar_value = 5
vector = np.array([1, 2, 3])
matrix = np.array([[4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

tensor_3d = np.array([[
                        [1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                      ],
                        
                      [
                        [10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]
                      ],
                        
                      [
                        [19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]
                      ]
])

# Scalar-tensor addition
scalar_tensor_result = scalar_value + tensor_3d

# Vector-tensor addition
vector_tensor_result = vector + tensor_3d

# Matrix-tensor addition
matrix_tensor_result = matrix + tensor_3d

# Display the original scalar, vector, matrix, tensor, and the results
print("Scalar Value:", scalar_value)
print("\nVector:")
print(vector)
print("\nMatrix:")
print(matrix)
print("\n3D Tensor:")
print(tensor_3d)
print("\nResult of Scalar-Tensor Addition:")
print(scalar_tensor_result)
print("\nResult of Vector-Tensor Addition:")
print(vector_tensor_result)
print("\nResult of Matrix-Tensor Addition:")
print(matrix_tensor_result)

Scalar Value: 5

Vector:
[1 2 3]

Matrix:
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

3D Tensor:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Result of Scalar-Tensor Addition:
[[[ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]]]

Result of Vector-Tensor Addition:
[[[ 2  4  6]
  [ 5  7  9]
  [ 8 10 12]]

 [[11 13 15]
  [14 16 18]
  [17 19 21]]

 [[20 22 24]
  [23 25 27]
  [26 28 30]]]

Result of Matrix-Tensor Addition:
[[[ 5  7  9]
  [11 13 15]
  [17 19 21]]

 [[14 16 18]
  [20 22 24]
  [26 28 30]]

 [[23 25 27]
  [29 31 33]
  [35 37 39]]]


And, as you can imagine, the numpy.sum function can be applied just as effectively in the case of tensors, following the same logic of summation along axes used in matrices.

**Example**

In [17]:
import numpy as np

# Manual definition of a 3D tensor
C = np.array([[
                      [1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]
                     ],
                     
                     [
                      [13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]
                     ],
                     
                     [
                      [25, 26, 27, 28],
                      [29, 30, 31, 32],
                      [33, 34, 35, 36]
                    ]
])

# Sum along each axis
C_sum_along_axis0 = np.sum(C, axis=0)
C_sum_along_axis1 = np.sum(C, axis=1)
C_sum_along_axis2 = np.sum(C, axis=2)

# Display the original tensor and the sums
print("Original Tensor:")
print(C)

print("\nSum along Axis 0:")
print(C_sum_along_axis0)

print("\nSum along Axis 1:")
print(C_sum_along_axis1)

print("\nSum along Axis 2:")
print(C_sum_along_axis2)


Original Tensor:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]

Sum along Axis 0:
[[39 42 45 48]
 [51 54 57 60]
 [63 66 69 72]]

Sum along Axis 1:
[[15 18 21 24]
 [51 54 57 60]
 [87 90 93 96]]

Sum along Axis 2:
[[ 10  26  42]
 [ 58  74  90]
 [106 122 138]]


## Conclusions

We explored the concept of algebraic object addition, delving into scalar, vector, matrix, and tensor additions using the versatile NumPy library in Python. We witnessed how these operations are performed element-wise, and we demonstrated examples showcasing the flexibility of handling objects with different shapes. It's crucial to note that these fundamental algebraic operations serve as the building blocks for various mathematical and computational concepts, particularly in the realm of Machine Learning.

Stay tuned for upcoming articles, where we will continue to delve into more advanced topics and applications within the exciting world of algebraic manipulations, providing valuable insights for your journey in data-driven exploration and analysis.